<?php
namespace Manage\Controller;
use Think\Controller;
use Home\Classlogic\Weixin_accountClasslogic;
use Home\Classlogic\Wechat_payClasslogic;
class VisitController extends BaseController {
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $wechat_config = M('wechat_config')->where(array('is_default'=>1))->find();
        $this->wechat_config = $wechat_config;
    }
    public function index(){
        import("@.ORG.Page");       //导入分页类
        $count  = M('visit_num')->count();    //计算总数
        $Page   = new \Think\Page($count, 2);
        $res   = M('visit_num')->limit($Page->firstRow. ',' . $Page->listRows)->order('visit_time desc')->select();
        $Page = $Page->show();// 分页显示输出
        $this->assign('Page',$Page);// 赋值分页输出
        $this->assign('res',$res);
        $this->display();
    }

}